"""Add username to users

Revision ID: 07bddfe8be35
Revises: e7cf10c8089b
Create Date: 2025-11-15 21:48:29.979773

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07bddfe8be35"
down_revision: Union[str, Sequence[str], None] = "e7cf10c8089b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("quantity_tovar", sa.Integer(), nullable=False))
    op.add_column("users", sa.Column("name", sa.String(length=100), nullable=False))
    op.add_column(
        "users", sa.Column("description", sa.String(length=500), nullable=True)
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.VARCHAR(length=50), nullable=False))
    op.add_column(
        "users", sa.Column("first_name", sa.VARCHAR(length=100), nullable=True)
    )
    op.add_column(
        "users", sa.Column("last_name", sa.VARCHAR(length=100), nullable=True)
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_column("users", "description")
    op.drop_column("users", "name")
    op.drop_column("products", "quantity_tovar")
    # ### end Alembic commands ###
